# Generated by Django 6.0.4 on 2026-04-30 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fix_is_deleted(apps, schema_editor):
    ProductCategory = apps.get_model('product', 'ProductCategory')
    ProductCategory.objects.filter(
        is_deleted__isnull=True
    ).update(is_deleted=False)


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0002_productcategory_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='created_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='updated_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(fix_is_deleted, migrations.RunPython.noop)
    ]
