# Generated by Django 6.0.4 on 2026-05-04 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productcategory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_product_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_product_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
